/*
=========================================================
|                                                       |
|   FLOR DE MARIA - SISTEMA DE GESTÃO INTEGRADO (SGI)   |
|   CÓDIGO JAVASCRIPT UNIFICADO                         |
|                                                       |
=========================================================
*/

// =======================================================
//  FILE: UTILS.JS
// =======================================================
class Utils {
    static formatCurrency(value) { if (typeof value !== 'number') { value = parseFloat(value) || 0; } return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value); }
    static parseCurrency(currencyString) { if (typeof currencyString === 'number') return currencyString; if (!currencyString) return 0; return parseFloat(currencyString.replace(/[^\d,-]/g, '').replace(',', '.')) || 0; }
    static formatDate(dateStr) { if (!dateStr) return ''; const date = new Date(dateStr); const userTimezoneOffset = date.getTimezoneOffset() * 60000; const correctedDate = new Date(date.getTime() + userTimezoneOffset); return new Intl.DateTimeFormat('pt-BR').format(correctedDate); }
    static formatDateTime(dateStr) { if (!dateStr) return ''; const date = new Date(dateStr); return new Intl.DateTimeFormat('pt-BR', { year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }).format(date); }
    static getCurrentDate() { return new Date().toISOString().split('T')[0]; }
    static generateId() { return Date.now().toString(36) + Math.random().toString(36).substr(2, 9); }
    static debounce(func, wait) { let timeout; return function executedFunction(...args) { const later = () => { clearTimeout(timeout); func(...args); }; clearTimeout(timeout); timeout = setTimeout(later, wait); }; }
    static isValidEmail(email) { const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/; return emailRegex.test(email); }
    static isValidPhone(phone) { const phoneRegex = /^\(\d{2}\) \d{4,5}-\d{4}$/; return phoneRegex.test(phone); }
    static formatPhone(phone) { const cleaned = (phone || '').replace(/\D/g, ''); const match = cleaned.match(/^(\d{2})(\d{4,5})(\d{4})$/); if (match) { return `(${match[1]}) ${match[2]}-${match[3]}`; } return phone; }
    static isValidCPF(cpf) { cpf = (cpf || '').replace(/\D/g, ''); if (cpf.length !== 11 || /^(\d)\1{10}$/.test(cpf)) { return false; } let sum = 0; for (let i = 0; i < 9; i++) { sum += parseInt(cpf.charAt(i)) * (10 - i); } let remainder = (sum * 10) % 11; if (remainder === 10) remainder = 0; if (remainder !== parseInt(cpf.charAt(9))) return false; sum = 0; for (let i = 0; i < 10; i++) { sum += parseInt(cpf.charAt(i)) * (11 - i); } remainder = (sum * 10) % 11; if (remainder === 10) remainder = 0; if (remainder !== parseInt(cpf.charAt(10))) return false; return true; }
    static formatCPF(cpf) { const cleaned = (cpf || '').replace(/\D/g, ''); const match = cleaned.match(/^(\d{3})(\d{3})(\d{3})(\d{2})$/); if (match) { return `${match[1]}.${match[2]}.${match[3]}-${match[4]}`; } return cpf; }
    static isOverdue(dateStr) { const today = new Date(); const compareDate = new Date(dateStr); today.setHours(0, 0, 0, 0); compareDate.setHours(23, 59, 59, 999); return compareDate < today; }
    static daysBetween(date1, date2) { const oneDay = 24 * 60 * 60 * 1000; return Math.round(Math.abs((new Date(date1) - new Date(date2)) / oneDay)); }
    static sanitizeHtml(str) { if (!str) return ''; const temp = document.createElement('div'); temp.textContent = str; return temp.innerHTML; }
    static downloadFile(content, filename, contentType = 'application/json') { const blob = new Blob([content], { type: contentType }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = filename; document.body.appendChild(link); link.click(); document.body.removeChild(link); URL.revokeObjectURL(url); }
    static formatFileSize(bytes) { if (bytes === 0) return '0 Bytes'; const k = 1024; const sizes = ['Bytes', 'KB', 'MB', 'GB']; const i = Math.floor(Math.log(bytes) / Math.log(k)); return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i]; }
    static getBrowserInfo() { const ua = navigator.userAgent; let browser = 'Unknown'; if (ua.includes('Chrome')) browser = 'Chrome'; else if (ua.includes('Firefox')) browser = 'Firefox'; else if (ua.includes('Safari')) browser = 'Safari'; else if (ua.includes('Edge')) browser = 'Edge'; else if (ua.includes('Opera')) browser = 'Opera'; return { browser, userAgent: ua, language: navigator.language, platform: navigator.platform }; }
    static generateWhatsAppLink(phone, message) { const cleanPhone = (phone || '').replace(/\D/g, ''); const encodedMessage = encodeURIComponent(message); return `https://wa.me/55${cleanPhone}?text=${encodedMessage}`; }
    static sortArray(array, field, direction = 'asc') { return [...array].sort((a, b) => { const aVal = a[field]; const bVal = b[field]; if (aVal < bVal) return direction === 'asc' ? -1 : 1; if (aVal > bVal) return direction === 'asc' ? 1 : -1; return 0; }); }
    static searchInArray(array, searchTerm, fields) { if (!searchTerm) return array; const term = searchTerm.toString().toLowerCase(); return array.filter(item => { return fields.some(field => { const value = item[field]; return value && value.toString().toLowerCase().includes(term); }); }); }
    static toSlug(text) { return text.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9 -]/g, '').replace(/\s+/g, '-').replace(/-+/g, '-').trim('-'); }
}

// =======================================================
//  FILE: STORAGE.JS
// =======================================================
class StorageManager {
    constructor() { this.storageKey = 'flordemaria_sgi_v2'; this.version = '2.0.0'; this.init(); }
    init() { const data = this.getAllData(); if (!data.version || data.version !== this.version) { this.migrateData(data); } }
    getAllData() { try { const data = localStorage.getItem(this.storageKey); return data ? JSON.parse(data) : this.getDefaultStructure(); } catch (error) { console.error('Error reading from storage:', error); return this.getDefaultStructure(); } }
    saveAllData(data) { try { data.version = this.version; data.lastUpdate = new Date().toISOString(); localStorage.setItem(this.storageKey, JSON.stringify(data)); return true; } catch (error) { console.error('Error saving to storage:', error); Notifications.error('Erro ao salvar dados. O armazenamento pode estar cheio.'); return false; } }
    getDefaultStructure() { return { version: this.version, createdAt: new Date().toISOString(), lastUpdate: new Date().toISOString(), clients: [], products: [], sales: [], cashFlow: [], expenses: [], receivables: [], settings: { storeName: 'Flor de Maria', ownerName: 'Maria', phone: '', address: '', lowStockAlert: 5, currency: 'BRL', autoBackup: false, showTips: true } }; }
    migrateData(oldData) { const newData = this.getDefaultStructure(); if (oldData.clients) newData.clients = oldData.clients; if (oldData.products) newData.products = oldData.products; if (oldData.sales) newData.sales = oldData.sales; if (oldData.cashFlow) newData.cashFlow = oldData.cashFlow; if (oldData.expenses) newData.expenses = oldData.expenses; if (oldData.receivables) newData.receivables = oldData.receivables; if (oldData.settings) { newData.settings = { ...newData.settings, ...oldData.settings }; } this.saveAllData(newData); console.log('Data migrated to version', this.version); }
    getClients() { return this.getAllData().clients || []; }
    getProducts() { return this.getAllData().products || []; }
    getSales() { return this.getAllData().sales || []; }
    getCashFlow() { return this.getAllData().cashFlow || []; }
    getExpenses() { return this.getAllData().expenses || []; }
    getReceivables() { return this.getAllData().receivables || []; }
    getSettings() { return this.getAllData().settings || {}; }
    saveClient(client) { const data = this.getAllData(); if (client.id) { const index = data.clients.findIndex(c => c.id === client.id); if (index > -1) data.clients[index] = { ...data.clients[index], ...client, updatedAt: new Date().toISOString() }; } else { client.id = Utils.generateId(); client.createdAt = new Date().toISOString(); client.updatedAt = client.createdAt; data.clients.push(client); } return this.saveAllData(data); }
    deleteClient(clientId) { const data = this.getAllData(); data.clients = data.clients.filter(c => c.id !== clientId); return this.saveAllData(data); }
    getClientById(clientId) { return this.getClients().find(c => c.id === clientId); }
    saveProduct(product) { const data = this.getAllData(); if (product.id) { const index = data.products.findIndex(p => p.id === product.id); if (index > -1) data.products[index] = { ...data.products[index], ...product, updatedAt: new Date().toISOString() }; } else { product.id = Utils.generateId(); product.createdAt = new Date().toISOString(); product.updatedAt = product.createdAt; data.products.push(product); } return this.saveAllData(data); }
    deleteProduct(productId) { const data = this.getAllData(); data.products = data.products.filter(p => p.id !== productId); return this.saveAllData(data); }
    updateProductStock(productId, quantityChange) { const data = this.getAllData(); const productIndex = data.products.findIndex(p => p.id === productId); if (productIndex !== -1) { data.products[productIndex].quantity += quantityChange; data.products[productIndex].updatedAt = new Date().toISOString(); return this.saveAllData(data); } return false; }
    saveSale(sale) { const data = this.getAllData(); sale.id = Utils.generateId(); sale.createdAt = new Date().toISOString(); sale.items.forEach(item => { const productIndex = data.products.findIndex(p => p.id === item.productId); if (productIndex !== -1) { data.products[productIndex].quantity -= item.quantity; data.products[productIndex].updatedAt = new Date().toISOString(); } }); if (sale.paymentMethod === 'cash' || sale.paymentMethod === 'pix') { data.cashFlow.push({ id: Utils.generateId(), description: `Venda #${sale.id.substr(-6)}`, type: 'income', amount: sale.total, date: sale.createdAt, category: 'sales', saleId: sale.id, createdAt: new Date().toISOString() }); } if ((sale.paymentMethod === 'credit' || sale.paymentMethod === 'card') && sale.installments >= 1) { const installmentValue = sale.total / sale.installments; for (let i = 1; i <= sale.installments; i++) { const dueDate = new Date(sale.createdAt); dueDate.setMonth(dueDate.getMonth() + i); data.receivables.push({ id: Utils.generateId(), clientId: sale.clientId, saleId: sale.id, description: `Parcela ${i}/${sale.installments} - Venda #${sale.id.substr(-6)}`, amount: installmentValue, dueDate: dueDate.toISOString(), status: 'pending', createdAt: new Date().toISOString() }); } } data.sales.push(sale); return this.saveAllData(data); }
    saveSettings(settings) { const data = this.getAllData(); data.settings = { ...data.settings, ...settings }; return this.saveAllData(data); }
    saveExpense(expense) { const data = this.getAllData(); if (expense.id) { const index = data.expenses.findIndex(e => e.id === expense.id); if(index > -1) { data.expenses[index] = {...data.expenses[index], ...expense, updatedAt: new Date().toISOString()}; const cashFlowIndex = data.cashFlow.findIndex(c => c.expenseId === expense.id); if (cashFlowIndex > -1) { data.cashFlow[cashFlowIndex].description = expense.description; data.cashFlow[cashFlowIndex].amount = expense.amount; data.cashFlow[cashFlowIndex].date = expense.date; } } } else { expense.id = Utils.generateId(); expense.createdAt = new Date().toISOString(); data.expenses.push(expense); data.cashFlow.push({ id: Utils.generateId(), description: expense.description, type: 'expense', amount: expense.amount, date: expense.date, category: 'expenses', expenseId: expense.id, createdAt: new Date().toISOString() }); } return this.saveAllData(data); }
    deleteExpense(expenseId) { const data = this.getAllData(); data.expenses = data.expenses.filter(e => e.id !== expenseId); data.cashFlow = data.cashFlow.filter(c => c.expenseId !== expenseId); return this.saveAllData(data); }
    markReceivableAsPaid(receivableId) { const data = this.getAllData(); const index = data.receivables.findIndex(r => r.id === receivableId); if (index > -1) { data.receivables[index].status = 'paid'; data.receivables[index].paidAt = new Date().toISOString(); data.cashFlow.push({ id: Utils.generateId(), description: data.receivables[index].description, type: 'income', amount: data.receivables[index].amount, date: new Date().toISOString(), category: 'receivables', receivableId, createdAt: new Date().toISOString() }); return this.saveAllData(data); } return false; }
    saveReceivable(receivable) { const data = this.getAllData(); if (receivable.id) { const index = data.receivables.findIndex(r => r.id === receivable.id); if(index > -1) data.receivables[index] = {...data.receivables[index], ...receivable, updatedAt: new Date().toISOString()}; } else { receivable.id = Utils.generateId(); receivable.createdAt = new Date().toISOString(); data.receivables.push(receivable); } return this.saveAllData(data); }
    deleteReceivable(receivableId){ const data = this.getAllData(); data.receivables = data.receivables.filter(r => r.id !== receivableId); return this.saveAllData(data); }
    exportBackup() { const data = this.getAllData(); return JSON.stringify({...data, exportedAt: new Date().toISOString(), exportedBy: `SGI v${this.version}`}, null, 2); }
    importBackup(backupDataString) { try { const data = JSON.parse(backupDataString); if (!data.version) throw new Error('Arquivo de backup inválido.'); this.saveAllData(data); return true; } catch(error) { console.error('Error importing backup:', error); return false; } }
    getStorageSize() { return new Blob([JSON.stringify(localStorage)]).size; }
    getStatistics() { const data = this.getAllData(); const now = new Date(); const currentMonth = now.getMonth(); const currentYear = now.getFullYear(); const currentMonthSales = data.sales.filter(s => { const saleDate = new Date(s.createdAt); return saleDate.getMonth() === currentMonth && saleDate.getFullYear() === currentYear; }); const currentMonthExpenses = data.expenses.filter(e => { const expenseDate = new Date(e.date); return expenseDate.getMonth() === currentMonth && expenseDate.getFullYear() === currentYear; }); const overdueReceivables = data.receivables.filter(r => r.status === 'pending' && Utils.isOverdue(r.dueDate)); const lowStockThreshold = data.settings.lowStockAlert || 5; return { totalClients: data.clients.length, totalProducts: data.products.length, totalSales: data.sales.length, currentBalance: data.cashFlow.reduce((bal, entry) => entry.type === 'income' ? bal + entry.amount : bal - entry.amount, 0), monthlyRevenue: currentMonthSales.reduce((sum, sale) => sum + sale.total, 0), monthlyExpenses: currentMonthExpenses.reduce((sum, exp) => sum + exp.amount, 0), totalReceivables: data.receivables.filter(r => r.status === 'pending').reduce((sum, r) => sum + r.amount, 0), overdueReceivables: overdueReceivables.length, lowStockProducts: data.products.filter(p => p.quantity > 0 && p.quantity <= lowStockThreshold).length }; }
}

// =======================================================
//  FILE: NOTIFICATIONS.JS
// =======================================================
class NotificationManager {
    constructor() { this.container = document.getElementById('notification-container'); if (!this.container) { this.container = document.createElement('div'); this.container.id = 'notification-container'; document.body.appendChild(this.container); } this.notifications = []; this.maxNotifications = 5; this.defaultDuration = 4000; }
    show(message, type = 'info', options = {}) { const id = Utils.generateId(); const duration = options.duration !== undefined ? options.duration : this.defaultDuration; const title = options.title || this.getDefaultTitle(type); const persistent = options.persistent || false; const notificationElement = document.createElement('div'); notificationElement.className = `toast ${type}`; notificationElement.dataset.id = id; notificationElement.innerHTML = `<div class="toast-icon"><i class="fas ${this.getIcon(type)}"></i></div><div class="toast-content"><div class="toast-title">${Utils.sanitizeHtml(title)}</div><div class="toast-message">${Utils.sanitizeHtml(message)}</div></div><button class="toast-close"><i class="fas fa-times"></i></button>`; notificationElement.querySelector('.toast-close').onclick = () => this.hide(id); const timeoutId = (persistent || duration <= 0) ? null : setTimeout(() => this.hide(id), duration); const notification = { id, element: notificationElement, timeoutId }; this.addNotification(notification); return id; }
    addNotification(notification) { if (this.notifications.length >= this.maxNotifications) { const oldest = this.notifications.shift(); this.hide(oldest.id, true); } this.notifications.push(notification); this.container.appendChild(notification.element); requestAnimationFrame(() => notification.element.classList.add('show')); }
    hide(id, immediate = false) { const index = this.notifications.findIndex(n => n.id === id); if (index === -1) return; const [notification] = this.notifications.splice(index, 1); if (notification.timeoutId) clearTimeout(notification.timeoutId); if (immediate) { if (notification.element.parentNode) notification.element.parentNode.removeChild(notification.element); } else { notification.element.classList.add('hiding'); notification.element.addEventListener('transitionend', () => { if (notification.element.parentNode) notification.element.parentNode.removeChild(notification.element); }); } }
    success(message, options = {}) { return this.show(message, 'success', options); }
    error(message, options = {}) { return this.show(message, 'error', { duration: 6000, ...options }); }
    info(message, options = {}) { return this.show(message, 'info', options); }
    warning(message, options = {}) { return this.show(message, 'warning', options); }
    showLoading(message = 'Carregando...') { return this.show(message, 'loading', { persistent: true, title: 'Aguarde' }); }
    hideLoading(id) { if (id) this.hide(id); }
    async confirm(message, title = 'Confirmação') { return new Promise(resolve => { const id = Utils.generateId(); const modalContent = `<div class="modal-header"><h3>${Utils.sanitizeHtml(title)}</h3></div><div class="modal-body"><p>${Utils.sanitizeHtml(message)}</p></div><div class="modal-footer"><button id="confirm-cancel-${id}" class="btn btn-secondary">Cancelar</button><button id="confirm-ok-${id}" class="btn btn-danger">Confirmar</button></div>`; app.showModal(modalContent); const okBtn = document.getElementById(`confirm-ok-${id}`); const cancelBtn = document.getElementById(`confirm-cancel-${id}`); okBtn.onclick = () => { app.closeModal(); resolve(true); }; cancelBtn.onclick = () => { app.closeModal(); resolve(false); }; }); }
    getDefaultTitle(type) { const titles = { success: 'Sucesso!', error: 'Erro!', warning: 'Atenção!', info: 'Informação', loading: 'Processando...' }; return titles[type] || 'Notificação'; }
    getIcon(type) { const icons = { success: 'fa-check-circle', error: 'fa-times-circle', warning: 'fa-exclamation-triangle', info: 'fa-info-circle', loading: 'fa-spinner fa-spin' }; return icons[type] || 'fa-bell'; }
}

// =======================================================
//  FILE: AUTH.JS
// =======================================================
class Auth {
    constructor() { this.credentials = { username: 'maria', password: '123' }; }
    init() { const loginForm = document.getElementById('login-form'); if (loginForm) { loginForm.addEventListener('submit', (e) => { e.preventDefault(); this.handleLogin(); }); } }
    async handleLogin() { const username = document.getElementById('username').value.trim(); const password = document.getElementById('password').value; if (username === this.credentials.username && password === this.credentials.password) { localStorage.setItem('flordemaria_auth', JSON.stringify({ authenticated: true, user: { username } })); if (window.app) window.app.onAuthenticationSuccess(); } else { Notifications.error('Usuário ou senha incorretos.'); } }
    static isAuthenticated() { const auth = localStorage.getItem('flordemaria_auth'); return auth && JSON.parse(auth).authenticated; }
    static getCurrentUser() { const auth = localStorage.getItem('flordemaria_auth'); return auth ? JSON.parse(auth).user : null; }
    static logout() { localStorage.removeItem('flordemaria_auth'); }
}

// =======================================================
//  MODULES (CLIENTS, INVENTORY, ETC.)
// =======================================================
class Clients {
    constructor() { this.clients = []; this.filteredClients = []; this.currentClient = null; this.searchTerm = ''; this.sortField = 'name'; this.sortDirection = 'asc'; }
    init() { this.bindEvents(); this.loadAndRender(); }
    bindEvents() { document.getElementById('add-client-btn')?.addEventListener('click', () => this.showClientForm()); const searchInput = document.getElementById('clients-search'); if (searchInput) { searchInput.addEventListener('input', Utils.debounce(e => { this.searchTerm = e.target.value; this.filterAndRender(); }, 300)); } document.querySelectorAll('#clients-table th[data-sort]').forEach(header => { header.addEventListener('click', () => { const field = header.dataset.sort; if (this.sortField === field) { this.sortDirection = this.sortDirection === 'asc' ? 'desc' : 'asc'; } else { this.sortField = field; this.sortDirection = 'asc'; } this.filterAndRender(); }); }); }
    loadAndRender() { this.clients = StorageManager.getClients(); this.filterAndRender(); }
    filterAndRender() { this.filteredClients = Utils.searchInArray(this.clients, this.searchTerm, ['name', 'phone', 'email', 'cpf']); this.filteredClients = Utils.sortArray(this.filteredClients, this.sortField, this.sortDirection); this.renderTable(); }
    renderTable() { const tbody = document.querySelector('#clients-table tbody'); if (!tbody) return; if (this.filteredClients.length === 0) { tbody.innerHTML = `<tr><td colspan="4" class="text-center">Nenhum cliente encontrado.</td></tr>`; return; } tbody.innerHTML = this.filteredClients.map(client => ` <tr data-client-id="${client.id}"> <td>${Utils.sanitizeHtml(client.name)}</td> <td>${Utils.sanitizeHtml(client.phone)}</td> <td>${Utils.formatDate(client.createdAt)}</td> <td> <div class="action-buttons"> <button class="btn btn-icon btn-primary" onclick="window.clients.editClient('${client.id}')" title="Editar"><i class="fas fa-edit"></i></button> <button class="btn btn-icon btn-danger" onclick="window.clients.deleteClient('${client.id}')" title="Excluir"><i class="fas fa-trash"></i></button> </div> </td> </tr> `).join(''); this.updateSortIcons(); }
    updateSortIcons() { document.querySelectorAll('#clients-table th[data-sort]').forEach(header => { header.innerHTML = header.textContent; if (header.dataset.sort === this.sortField) { const iconClass = this.sortDirection === 'asc' ? 'fa-sort-up' : 'fa-sort-down'; header.innerHTML += ` <i class="fas ${iconClass}"></i>`; } }); }
    showClientForm(client = null) { this.currentClient = client; const isEdit = !!client; const modalContent = `<div class="modal-header"><h3>${isEdit ? 'Editar Cliente' : 'Novo Cliente'}</h3></div><div class="modal-body"><form id="client-form"><div class="form-group"><label>Nome *</label><input type="text" id="client-name" class="form-control" value="${client ? Utils.sanitizeHtml(client.name) : ''}" required></div><div class="form-group"><label>Telefone</label><input type="tel" id="client-phone" class="form-control" value="${client ? Utils.sanitizeHtml(client.phone || '') : ''}"></div><div class="form-group"><label>E-mail</label><input type="email" id="client-email" class="form-control" value="${client ? Utils.sanitizeHtml(client.email || '') : ''}"></div><div class="form-group"><label>CPF</label><input type="text" id="client-cpf" class="form-control" value="${client ? Utils.sanitizeHtml(client.cpf || '') : ''}"></div><div class="form-group"><label>Endereço</label><textarea id="client-address" class="form-control">${client ? Utils.sanitizeHtml(client.address || '') : ''}</textarea></div></form></div><div class="modal-footer"><button type="button" class="btn btn-secondary modal-close">Cancelar</button><button type="button" class="btn btn-primary" id="save-client-btn">Salvar</button></div>`; app.showModal(modalContent); document.getElementById('save-client-btn').onclick = () => this.saveClient(); }
    async saveClient() { const name = document.getElementById('client-name').value.trim(); if (!name) { Notifications.error('O nome do cliente é obrigatório.'); return; } const clientData = { id: this.currentClient ? this.currentClient.id : null, name: name, phone: document.getElementById('client-phone').value.trim(), email: document.getElementById('client-email').value.trim(), cpf: document.getElementById('client-cpf').value.trim(), address: document.getElementById('client-address').value.trim(), }; if (window.StorageManager.saveClient(clientData)) { Notifications.success(`Cliente ${this.currentClient ? 'atualizado' : 'cadastrado'} com sucesso!`); app.closeModal(); this.refresh(); } }
    async deleteClient(clientId) { const client = this.clients.find(c => c.id === clientId); if (!client) return; const confirmed = await Notifications.confirm(`Tem certeza que deseja excluir o cliente "${client.name}"?`); if (confirmed) { if (window.StorageManager.deleteClient(clientId)) { Notifications.success('Cliente excluído com sucesso!'); this.refresh(); } } }
    editClient(clientId) { const client = this.clients.find(c => c.id === clientId); if (client) this.showClientForm(client); }
    refresh() { this.loadAndRender(); }
}
class Inventory {
    constructor() { this.products = []; this.filteredProducts = []; this.currentProduct = null; this.searchTerm = ''; this.sortField = 'name'; this.sortDirection = 'asc'; }
    init() { this.bindEvents(); this.loadAndRender(); }
    bindEvents() { document.getElementById('add-product-btn')?.addEventListener('click', () => this.showProductForm()); const searchInput = document.getElementById('inventory-search'); if (searchInput) { searchInput.addEventListener('input', Utils.debounce(e => { this.searchTerm = e.target.value; this.filterAndRender(); }, 300)); } document.querySelectorAll('#inventory-table th[data-sort]').forEach(header => { header.addEventListener('click', () => { const field = header.dataset.sort; if (this.sortField === field) { this.sortDirection = this.sortDirection === 'asc' ? 'desc' : 'asc'; } else { this.sortField = field; this.sortDirection = 'asc'; } this.filterAndRender(); }); }); }
    loadAndRender() { this.products = StorageManager.getProducts(); this.filterAndRender(); }
    filterAndRender() { this.filteredProducts = Utils.searchInArray(this.products, this.searchTerm, ['code', 'name']); this.filteredProducts = Utils.sortArray(this.filteredProducts, this.sortField, this.sortDirection); this.renderTable(); }
    renderTable() { const tbody = document.querySelector('#inventory-table tbody'); if (!tbody) return; if (this.filteredProducts.length === 0) { tbody.innerHTML = `<tr><td colspan="7" class="text-center">Nenhum produto encontrado.</td></tr>`; return; } tbody.innerHTML = this.filteredProducts.map(product => ` <tr data-product-id="${product.id}"> <td>${Utils.sanitizeHtml(product.code)}</td> <td>${Utils.sanitizeHtml(product.name)}</td> <td>${product.quantity}</td> <td>${Utils.formatCurrency(product.costPrice)}</td> <td>${Utils.formatCurrency(product.salePrice)}</td> <td><span class="status-badge ${product.quantity > 0 ? 'status-available' : 'status-out-of-stock'}">${product.quantity > 0 ? 'Disponível' : 'Esgotado'}</span></td> <td> <div class="action-buttons"> <button class="btn btn-icon btn-primary" onclick="window.inventory.editProduct('${product.id}')" title="Editar"><i class="fas fa-edit"></i></button> <button class="btn btn-icon btn-danger" onclick="window.inventory.deleteProduct('${product.id}')" title="Excluir"><i class="fas fa-trash"></i></button> </div> </td> </tr> `).join(''); this.updateSortIcons(); }
    updateSortIcons() { document.querySelectorAll('#inventory-table th[data-sort]').forEach(header => { header.innerHTML = header.textContent; if (header.dataset.sort === this.sortField) { const iconClass = this.sortDirection === 'asc' ? 'fa-sort-up' : 'fa-sort-down'; header.innerHTML += ` <i class="fas ${iconClass}"></i>`; } }); }
    showProductForm(product = null) { this.currentProduct = product; const isEdit = !!product; const modalContent = `<div class="modal-header"><h3>${isEdit ? 'Editar Produto' : 'Novo Produto'}</h3></div><div class="modal-body"><form id="product-form"><div class="form-group"><label>Código *</label><input type="text" id="product-code" class="form-control" value="${product ? Utils.sanitizeHtml(product.code) : ''}" required></div><div class="form-group"><label>Nome *</label><input type="text" id="product-name" class="form-control" value="${product ? Utils.sanitizeHtml(product.name) : ''}" required></div><div class="form-group"><label>Quantidade *</label><input type="number" id="product-quantity" class="form-control" value="${product ? product.quantity : '0'}" required></div><div class="form-group"><label>Preço de Custo *</label><input type="number" id="product-cost" class="form-control" value="${product ? product.costPrice : ''}" required></div><div class="form-group"><label>Preço de Venda *</label><input type="number" id="product-sale" class="form-control" value="${product ? product.salePrice : ''}" required></div></form></div><div class="modal-footer"><button type="button" class="btn btn-secondary modal-close">Cancelar</button><button type="button" class="btn btn-primary" id="save-product-btn">Salvar</button></div>`; app.showModal(modalContent); document.getElementById('save-product-btn').onclick = () => this.saveProduct(); }
    async saveProduct() { const code = document.getElementById('product-code').value.trim(); const name = document.getElementById('product-name').value.trim(); const quantity = parseInt(document.getElementById('product-quantity').value); const costPrice = parseFloat(document.getElementById('product-cost').value); const salePrice = parseFloat(document.getElementById('product-sale').value); if (!code || !name || isNaN(quantity) || isNaN(costPrice) || isNaN(salePrice)) { Notifications.error('Todos os campos marcados com * são obrigatórios.'); return; } const productData = { id: this.currentProduct ? this.currentProduct.id : null, code, name, quantity, costPrice, salePrice }; if (window.StorageManager.saveProduct(productData)) { Notifications.success(`Produto ${this.currentProduct ? 'atualizado' : 'cadastrado'} com sucesso!`); app.closeModal(); this.refresh(); } }
    async deleteProduct(productId) { const product = this.products.find(p => p.id === productId); if (!product) return; const confirmed = await Notifications.confirm(`Tem certeza que deseja excluir o produto "${product.name}"?`); if (confirmed) { if (window.StorageManager.deleteProduct(productId)) { Notifications.success('Produto excluído com sucesso!'); this.refresh(); } } }
    editProduct(productId) { const product = this.products.find(p => p.id === productId); if (product) this.showProductForm(product); }
    refresh() { this.loadAndRender(); }
}
class Dashboard { init(){} refresh(){} }
class Sales { init(){} refresh(){} }
class CashFlow { init(){} refresh(){} }
class Expenses { init(){} refresh(){} }
class Receivables { init(){} refresh(){} }
class Reports { init(){} refresh(){} }
class Settings { init(){} refresh(){} }

// =======================================================
//  FILE: APP.JS (MAIN CONTROLLER)
// =======================================================
class App {
    constructor() { this.currentModule = 'dashboard'; this.isAuthenticated = false; this.isMobile = window.innerWidth <= 768; this.sidebarCollapsed = localStorage.getItem('sidebarCollapsed') === 'true'; this.modules = {}; }
    init() { this.bindEvents(); this.setupResponsive(); this.checkAuthentication(); }
    bindEvents() { document.getElementById('sidebar-toggle')?.addEventListener('click', () => this.toggleSidebar()); document.querySelectorAll('.nav-item').forEach(item => { item.addEventListener('click', (e) => { e.preventDefault(); const module = item.dataset.module; if (module) this.showModule(module); }); }); document.getElementById('logout-btn')?.addEventListener('click', () => this.logout()); document.addEventListener('click', (e) => { if (e.target.closest('.modal-close')) this.closeModal(); if (this.isMobile && document.getElementById('sidebar') && !document.getElementById('sidebar').contains(e.target) && document.getElementById('sidebar-toggle') && !document.getElementById('sidebar-toggle').contains(e.target)) { this.closeSidebar(); } }); document.addEventListener('keydown', (e) => { if (e.key === 'Escape') { this.closeModal(); if (this.isMobile) this.closeSidebar(); } }); window.addEventListener('resize', Utils.debounce(() => this.handleResize(), 250)); }
    setupResponsive() { this.isMobile = window.innerWidth <= 768; const mainApp = document.getElementById('main-app'); if (mainApp) { if (this.isMobile) { mainApp.classList.remove('sidebar-collapsed'); } else { mainApp.classList.toggle('sidebar-collapsed', this.sidebarCollapsed); } } }
    handleResize() { const mobileState = this.isMobile; this.setupResponsive(); }
    checkAuthentication() { this.isAuthenticated = Auth.isAuthenticated(); this.updateUI(); if (this.isAuthenticated) { this.onAuthenticationSuccess(); } else { if (window.auth) window.auth.init(); } }
    onAuthenticationSuccess() { this.isAuthenticated = true; this.updateUI(); this.initializeModules(); this.showModule('dashboard'); const user = Auth.getCurrentUser(); if (user) Notifications.success(`Bem-vinda de volta, ${user.username}!`, { title: 'Login realizado' }); }
    updateUI() { const loginScreen = document.getElementById('login-screen'); const mainApp = document.getElementById('main-app'); if (loginScreen) loginScreen.classList.toggle('hidden', this.isAuthenticated); if (mainApp) mainApp.classList.toggle('hidden', !this.isAuthenticated); }
    initializeModules() { if (!this.isAuthenticated) return; this.modules = { dashboard: new Dashboard(), clients: new Clients(), inventory: new Inventory(), sales: new Sales(), cashflow: new CashFlow(), expenses: new Expenses(), receivables: new Receivables(), reports: new Reports(), settings: new Settings() }; for (const moduleName in this.modules) { window[moduleName] = this.modules[moduleName]; if (typeof this.modules[moduleName].init === 'function') { this.modules[moduleName].init(); } } }
    showModule(moduleName) { if (!this.isAuthenticated || !this.modules[moduleName]) return; document.querySelectorAll('.module.active').forEach(m => m.classList.remove('active')); document.getElementById(`${moduleName}-module`)?.classList.add('active'); document.querySelectorAll('.nav-item.active').forEach(item => item.classList.remove('active')); document.querySelector(`.nav-item[data-module="${moduleName}"]`)?.classList.add('active'); this.currentModule = moduleName; if (typeof this.modules[moduleName].refresh === 'function') { this.modules[moduleName].refresh(); } if (this.isMobile) this.closeSidebar(); this.updatePageTitle(moduleName); }
    updatePageTitle(moduleName) { const titles = { dashboard: 'Dashboard', clients: 'Clientes', inventory: 'Estoque', sales: 'Vendas (PDV)', cashflow: 'Fluxo de Caixa', expenses: 'Despesas', receivables: 'Contas a Receber', reports: 'Relatórios', settings: 'Configurações' }; document.title = `${titles[moduleName] || 'Sistema'} - Flor de Maria SGI`; }
    toggleSidebar() { if (this.isMobile) { document.getElementById('sidebar')?.classList.toggle('open'); } else { this.sidebarCollapsed = !this.sidebarCollapsed; document.getElementById('main-app')?.classList.toggle('sidebar-collapsed', this.sidebarCollapsed); localStorage.setItem('sidebarCollapsed', this.sidebarCollapsed); } }
    closeSidebar() { if (this.isMobile) { document.getElementById('sidebar')?.classList.remove('open'); } }
    showModal(content) { const modalOverlay = document.getElementById('modal-overlay'); const modalContent = document.getElementById('modal-content'); if (modalOverlay && modalContent) { modalContent.innerHTML = content; modalOverlay.classList.remove('hidden'); const firstFocusable = modalContent.querySelector('button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'); if (firstFocusable) firstFocusable.focus(); } }
    closeModal() { const modalOverlay = document.getElementById('modal-overlay'); if (modalOverlay) { modalOverlay.classList.add('hidden'); document.getElementById('modal-content').innerHTML = ''; } }
    logout() { Auth.logout(); this.isAuthenticated = false; window.location.reload(); }
}


// =======================================================
//  INITIALIZATION
// =======================================================
document.addEventListener('DOMContentLoaded', () => {
    // These instances need to be available globally for the inline `onclick` attributes in the HTML
    window.StorageManager = new StorageManager();
    window.Notifications = new NotificationManager();
    window.auth = new Auth();
    window.app = new App();
    
    // Start the app
    window.app.init();
});
